/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PeriodicNotesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/commands/note_update.ts
var import_obsidian2 = require("obsidian");

// src/repository/repo.ts
var import_obsidian = require("obsidian");
var Repo = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  async find(graph, name, create = true) {
    let reqFile;
    if (graph.path.includes("Void") && name.split(".").length === 1) {
      reqFile = graph.files.find((file) => file.basename === name);
    } else {
      reqFile = graph.files.find((file) => file.basename.endsWith(name));
    }
    if (!reqFile) {
      if (create) {
        reqFile = await this.createAndUpdateFile(graph, name);
        await new Promise((resolve) => setTimeout(resolve, 50));
        const freshFile = this.plugin.app.vault.getAbstractFileByPath(reqFile.path);
        if (freshFile instanceof import_obsidian.TFile) {
          reqFile = freshFile;
        }
      } else {
        console.error(`\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u043D\u0430\u0439\u0442\u0438: "${name}" \u0432 "${graph.path}"`);
        return null;
      }
    }
    const reqFileName = reqFile.basename;
    const reqFileText = await this.plugin.app.vault.read(reqFile);
    return [reqFileName, reqFileText];
  }
  async createAndUpdateFile(graph, name) {
    let createdFile;
    try {
      createdFile = await this.plugin.app.vault.create(graph.path + name + ".md", "\n# temp");
      console.log(`\u0417\u0430\u043C\u0435\u0442\u043A\u0430 "${name}" \u0441\u043E\u0437\u0434\u0430\u043D\u0430 \u0432 "${graph.path}"`);
    } catch (error) {
      console.error(`\u041E\u0448\u0438\u0431\u043A\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u044F "${name}": ${error}`);
      throw error;
    }
    const insertIndex = graph.files.findIndex(
      (file) => file.basename.localeCompare(createdFile.basename) > 0
    );
    if (insertIndex === -1) {
      graph.files.push(createdFile);
    } else {
      graph.files.splice(insertIndex, 0, createdFile);
    }
    return createdFile;
  }
  createGraph(files, path, alias) {
    return {
      files,
      path,
      alias
    };
  }
};

// src/models/note/note.ts
var Note = class {
  constructor(name, text) {
    this.name = name;
    this.words = this.parseWords();
    this.title = this.parseTitle();
    this.body = this.parseBody(text);
  }
  parseWords() {
    return this.name.split(".");
  }
  parseTitle() {
    var _a;
    return (_a = this.words[this.words.length - 1]) != null ? _a : this.name;
  }
  parseBody(text) {
    var _a;
    return (_a = text.split(/^# .*$/gm).pop()) != null ? _a : text;
  }
  async findFounder(repo, graph, _celestia) {
    const founderName = this.words[0];
    console.log(`Note founder: "${founderName}"`);
    return await repo.find(graph, founderName, true);
  }
  async findFather(repo, graph, celestia) {
    var _a;
    if (this.words.length > 1) {
      const fatherName = this.words.slice(0, -1).join(".");
      const fatherTitle = (_a = this.words[this.words.length - 2]) != null ? _a : fatherName;
      console.log(`Note father: "${fatherName}" (stub)`);
      return [fatherName, `# ${fatherTitle}
`];
    }
    return this.findFounder(repo, graph, celestia);
  }
};

// src/models/note/periodic/periodic.ts
var Periodic = class extends Note {
};

// src/models/note/periodic/dates/daily.ts
var Daily = class extends Periodic {
  async findFounder(repo, GRAPH, CELESTIA) {
    const plugin = repo.plugin;
    if (this.name === plugin.settings.periodic.templates.daily) {
      return await repo.find(CELESTIA, plugin.settings.periodic.celestia_paths.daily);
    }
    return await repo.find(GRAPH, plugin.settings.periodic.templates.daily);
  }
  async findFather(repo, GRAPH, CELESTIA) {
    return this.findFounder(repo, GRAPH, CELESTIA);
  }
};

// src/models/note/periodic/dates/weekly.ts
var Weekly = class extends Periodic {
  async findFounder(repo, GRAPH, CELESTIA) {
    const plugin = repo.plugin;
    if (this.name === plugin.settings.periodic.templates.weekly) {
      return await repo.find(CELESTIA, plugin.settings.periodic.celestia_paths.weekly);
    }
    return await repo.find(GRAPH, plugin.settings.periodic.templates.weekly);
  }
  async findFather(repo, GRAPH, CELESTIA) {
    return this.findFounder(repo, GRAPH, CELESTIA);
  }
};

// src/models/note/periodic/dates/monthly.ts
var Monthly = class extends Periodic {
  async findFounder(repo, GRAPH, CELESTIA) {
    const plugin = repo.plugin;
    if (this.name === plugin.settings.periodic.templates.monthly) {
      return await repo.find(CELESTIA, plugin.settings.periodic.celestia_paths.monthly);
    }
    return await repo.find(GRAPH, plugin.settings.periodic.templates.monthly);
  }
  async findFather(repo, GRAPH, CELESTIA) {
    return this.findFounder(repo, GRAPH, CELESTIA);
  }
};

// src/models/note/periodic/dates/quarterly.ts
var Quarterly = class extends Periodic {
  async findFounder(repo, GRAPH, CELESTIA) {
    const plugin = repo.plugin;
    if (this.name === plugin.settings.periodic.templates.quarterly) {
      return await repo.find(CELESTIA, plugin.settings.periodic.celestia_paths.quarterly);
    }
    return await repo.find(GRAPH, plugin.settings.periodic.templates.quarterly);
  }
  async findFather(repo, GRAPH, CELESTIA) {
    return this.findFounder(repo, GRAPH, CELESTIA);
  }
};

// src/models/note/periodic/dates/yearly.ts
var Yearly = class extends Periodic {
  async findFounder(repo, GRAPH, CELESTIA) {
    const plugin = repo.plugin;
    if (this.name === plugin.settings.periodic.templates.yearly) {
      return await repo.find(CELESTIA, plugin.settings.periodic.celestia_paths.yearly);
    }
    return await repo.find(GRAPH, plugin.settings.periodic.templates.yearly);
  }
  async findFather(repo, GRAPH, CELESTIA) {
    return this.findFounder(repo, GRAPH, CELESTIA);
  }
};

// src/models/note/periodic/event/dream.ts
var Dream = class extends Periodic {
};

// src/models/note/periodic/event/thought.ts
var Thought = class extends Periodic {
};

// src/utils/services/validator.ts
var Validator = class {
  static isDream(note) {
    return note.title.startsWith("\u0441\u043E\u043D.");
  }
  static isThought(note) {
    return note.title.startsWith("\u043C\u044B\u0441\u043B\u044C.");
  }
  static isDaily(note) {
    return /^\d{4}-\d{2}-\d{2}$/.test(note.title);
  }
  static isWeekly(note) {
    return /^\d{4}-W\d{2}$/.test(note.title);
  }
  static isMonthly(note) {
    return /^\d{4}-\d{2}$/.test(note.title);
  }
  static isQuarterly(note) {
    return /^\d{4}-Q\d{1}$/.test(note.title);
  }
  static isYearly(note) {
    return /^\d{4}$/.test(note.title);
  }
  static hasDate(note) {
    const match = note.name.match(/(\d{4}-\d{2}-\d{2})/);
    return match ? [match[1], true] : [null, false];
  }
  static hasWeek(note) {
    const match = note.name.match(/(\d{4}-W\d{2})/);
    return match ? [match[1], true] : [null, false];
  }
  static hasMonth(note) {
    const match = note.name.match(/(\d{4}-\d{2})/);
    return match ? [match[1], true] : [null, false];
  }
  static hasQuarter(note) {
    const match = note.name.match(/(\d{4}-Q\d{1})/);
    return match ? [match[1], true] : [null, false];
  }
  static hasYear(note) {
    const match = note.name.match(/(\d{4})/);
    return match ? [match[1], true] : [null, false];
  }
};
function createNote(title, text, plugin) {
  const note = new Note(title, text);
  if (Validator.isThought(note) && plugin) {
    return new Thought(title, text);
  } else if (Validator.isDream(note) && plugin) {
    return new Dream(title, text);
  } else if (Validator.isDaily(note)) {
    return new Daily(title, text);
  } else if (Validator.isWeekly(note)) {
    return new Weekly(title, text);
  } else if (Validator.isMonthly(note)) {
    return new Monthly(title, text);
  } else if (Validator.isQuarterly(note)) {
    return new Quarterly(title, text);
  } else if (Validator.isYearly(note)) {
    return new Yearly(title, text);
  }
  return note;
}

// src/utils/services/linker.ts
function createLink(note, alias) {
  return `[${alias}:: [[${note.name}#${note.title}|${note.title}]]]`;
}
var Linker = class {
  constructor(repository) {
    this.repository = repository;
  }
  async link(note, graph, celestia) {
    const connections = await this.findConnections(note, graph, celestia);
    return this.formatLinks(connections, note, graph);
  }
  async findConnections(note, graph, celestia) {
    let founder;
    let father;
    if (note.words.length === 1 && this.isPeriodic(note)) {
      const isTemplate = this.isTemplate(note);
      const targetGraph = isTemplate ? celestia : graph;
      const founderResult = await note.findFounder(this.repository, targetGraph, celestia);
      if (!founderResult) throw new Error(`Founder not found for ${note.title}`);
      const [founderName, founderText] = founderResult;
      founder = new Note(founderName, founderText);
      const fatherResult = await note.findFather(this.repository, targetGraph, celestia);
      if (!fatherResult) throw new Error(`Father not found for ${note.title}`);
      const [fatherName, fatherText] = fatherResult;
      father = new Note(fatherName, fatherText);
    } else if (note.words.length === 1) {
      const founderResult = await note.findFounder(this.repository, celestia, celestia);
      if (!founderResult) throw new Error(`Founder not found for ${note.title}`);
      const [founderName, founderText] = founderResult;
      founder = new Note(founderName, founderText);
      father = founder;
    } else {
      const founderResult = await note.findFounder(this.repository, graph, celestia);
      if (!founderResult) throw new Error(`Founder not found for ${note.title}`);
      const [founderName, founderText] = founderResult;
      founder = new Note(founderName, founderText);
      const fatherResult = await note.findFather(this.repository, graph, celestia);
      if (!fatherResult) throw new Error(`Father not found for ${note.title}`);
      const [fatherName, fatherText] = fatherResult;
      father = new Note(fatherName, fatherText);
    }
    return { founder, father };
  }
  isPeriodic(note) {
    return Validator.isDaily(note) || Validator.isWeekly(note) || Validator.isMonthly(note) || Validator.isQuarterly(note) || Validator.isYearly(note);
  }
  isTemplate(note) {
    return note.title === "0000-00-00" || note.title === "0000-W00" || note.title === "0000-00" || note.title === "0000-Q0" || note.title === "0000";
  }
  formatLinks(connections, note, graph) {
    const { founder, father } = connections;
    const links = [
      createLink(founder, graph.alias.founder),
      createLink(father, graph.alias.father)
    ];
    const ancestorLinks = this.generateAncestorLinks(note, graph);
    if (ancestorLinks) {
      links.push(ancestorLinks);
    }
    return links.join("\n");
  }
  generateAncestorLinks(note, graph) {
    const links = [];
    const isDaily = Validator.isDaily(note);
    const isWeekly = Validator.isWeekly(note);
    const isMonthly = Validator.isMonthly(note);
    const isQuarterly = Validator.isQuarterly(note);
    const isYearly = Validator.isYearly(note);
    if (isDaily) {
      const date2 = note.title;
      const week2 = this.getWeekFromDate(date2);
      if (week2) {
        links.push(`[${graph.alias.ancestor}:: [[${week2}#${week2}|${week2}]]]`);
      }
      const month2 = date2.slice(0, 7);
      links.push(`[${graph.alias.ancestor}:: [[${month2}#${month2}|${month2}]]]`);
      const quarter2 = this.getQuarterFromDate(date2);
      if (quarter2) {
        links.push(`[${graph.alias.ancestor}:: [[${quarter2}#${quarter2}|${quarter2}]]]`);
      }
      const year = date2.slice(0, 4);
      links.push(`[${graph.alias.ancestor}:: [[${year}#${year}|${year}]]]`);
      return links.join("\n");
    }
    if (isWeekly) {
      const week2 = note.title;
      const month2 = this.getMonthFromWeek(week2);
      if (month2) {
        links.push(`[${graph.alias.ancestor}:: [[${month2}#${month2}|${month2}]]]`);
      }
      const quarter2 = this.getQuarterFromWeek(week2);
      if (quarter2) {
        links.push(`[${graph.alias.ancestor}:: [[${quarter2}#${quarter2}|${quarter2}]]]`);
      }
      const year = week2.slice(0, 4);
      links.push(`[${graph.alias.ancestor}:: [[${year}#${year}|${year}]]]`);
      return links.join("\n");
    }
    if (isMonthly) {
      const month2 = note.title;
      const quarter2 = this.getQuarterFromMonth(month2);
      if (quarter2) {
        links.push(`[${graph.alias.ancestor}:: [[${quarter2}#${quarter2}|${quarter2}]]]`);
      }
      const year = month2.slice(0, 4);
      links.push(`[${graph.alias.ancestor}:: [[${year}#${year}|${year}]]]`);
      return links.join("\n");
    }
    if (isQuarterly) {
      const quarter2 = note.title;
      const yearMatch = quarter2.match(/^(\d{4})/);
      if (yearMatch) {
        const year = yearMatch[1];
        links.push(`[${graph.alias.ancestor}:: [[${year}#${year}|${year}]]]`);
      }
      return links.join("\n");
    }
    if (isYearly) {
      return "";
    }
    const [date, hasDate] = Validator.hasDate(note);
    if (hasDate && date !== null) {
      return `[${graph.alias.ancestor}:: [[${date}#${date}|${date}]]]`;
    }
    const [week, hasWeek] = Validator.hasWeek(note);
    if (hasWeek && week !== null) {
      return `[${graph.alias.ancestor}:: [[${week}#${week}|${week}]]]`;
    }
    const [month, hasMonth] = Validator.hasMonth(note);
    if (hasMonth && month !== null) {
      return `[${graph.alias.ancestor}:: [[${month}#${month}|${month}]]]`;
    }
    const [quarter, hasQuarter] = Validator.hasQuarter(note);
    if (hasQuarter && quarter !== null) {
      return `[${graph.alias.ancestor}:: [[${quarter}#${quarter}|${quarter}]]]`;
    }
    return "";
  }
  getWeekFromDate(dateStr) {
    const date = new Date(dateStr);
    if (isNaN(date.getTime())) return null;
    const day = date.getDay() || 7;
    date.setDate(date.getDate() + 4 - day);
    const yearStart = new Date(date.getFullYear(), 0, 1);
    const diff = (date.getTime() - yearStart.getTime()) / 864e5;
    const week = Math.ceil((diff + 1) / 7);
    return `${date.getFullYear()}-W${String(week).padStart(2, "0")}`;
  }
  getQuarterFromDate(dateStr) {
    const match = dateStr.match(/^(\d{4})-(\d{2})/);
    if (!match) return null;
    const quarter = Math.ceil(parseInt(match[2]) / 3);
    return `${match[1]}-Q${quarter}`;
  }
  getMonthFromWeek(weekTitle) {
    const match = weekTitle.match(/^(\d{4})-W(\d{2})$/);
    if (!match) return null;
    const year = parseInt(match[1]);
    const week = parseInt(match[2]);
    const jan4 = new Date(year, 0, 4);
    const firstWeekStart = new Date(
      jan4.getTime() - (jan4.getDay() || 7 - 1) * 24 * 60 * 60 * 1e3
    );
    const weekStart = new Date(firstWeekStart.getTime() + (week - 1) * 7 * 24 * 60 * 60 * 1e3);
    const monthNum = String(weekStart.getMonth() + 1).padStart(2, "0");
    return `${weekStart.getFullYear()}-${monthNum}`;
  }
  getQuarterFromWeek(weekTitle) {
    const month = this.getMonthFromWeek(weekTitle);
    return month ? this.getQuarterFromMonth(month) : null;
  }
  getQuarterFromMonth(monthTitle) {
    const match = monthTitle.match(/^(\d{4})-(\d{2})$/);
    if (!match) return null;
    const quarter = Math.ceil(parseInt(match[2]) / 3);
    return `${match[1]}-Q${quarter}`;
  }
};

// src/utils/services/tager.ts
var Tager = class {
  constructor(repository) {
    this.repository = repository;
  }
  async tag(note, graph, celestia) {
    return this.getMainTag(note, graph, celestia);
  }
  async getMainTag(note, graph, celestia) {
    const plugin = this.repository.plugin;
    const founderResult = await note.findFounder(this.repository, graph, celestia);
    if (!founderResult) {
      return "";
    }
    const [founderName, founderText] = founderResult;
    const founderNote = createNote(founderName, founderText, plugin);
    const rootResult = await founderNote.findFounder(this.repository, celestia, celestia);
    if (!rootResult) {
      return "";
    }
    const [rootName] = rootResult;
    for (const [marker, tagName] of Object.entries(plugin.settings.tags.mapping)) {
      if (rootName.includes(marker)) {
        return `#${tagName}`;
      }
    }
    return "";
  }
};

// src/utils/services/updater.ts
var Updater = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  async update(file, graph, celestia) {
    console.log(`
---------------------------
"${file.basename}"
---------------------------`);
    const repository = new Repo(this.plugin);
    const name = file.basename;
    const text = await this.plugin.app.vault.read(file);
    const note = createNote(name, text, this.plugin);
    const linker = new Linker(repository);
    const tager = new Tager(repository);
    const links = await linker.link(note, graph, celestia);
    const tags = await tager.tag(note, graph, celestia);
    const newText = this.formatNoteText(note, links, tags);
    await this.plugin.app.vault.modify(file, newText);
  }
  formatNoteText(note, links, tags) {
    return [links, `
${tags}
`, `# ${note.title}${note.body}`].join("\n");
  }
};

// src/commands/note_update.ts
async function updateNoteLinks(plugin) {
  const repository = new Repo(plugin);
  const allFiles = plugin.app.vault.getMarkdownFiles();
  const voidFiles = allFiles.filter(
    (file2) => file2.path.startsWith(plugin.settings.paths.void)
  );
  const celestiaFiles = allFiles.filter(
    (file2) => file2.path.startsWith(plugin.settings.paths.celestia)
  );
  const VOID = repository.createGraph(
    voidFiles,
    plugin.settings.paths.void,
    plugin.settings.aliases.void
  );
  const CELESTIA = repository.createGraph(
    celestiaFiles,
    plugin.settings.paths.celestia,
    plugin.settings.aliases.celestia
  );
  VOID.files.sort((a, b) => a.basename.localeCompare(b.basename));
  CELESTIA.files.sort((a, b) => a.basename.localeCompare(b.basename));
  const file = plugin.app.workspace.getActiveFile();
  if (!file) {
    new import_obsidian2.Notice("\u041D\u0435\u0442 \u0430\u043A\u0442\u0438\u0432\u043D\u043E\u0433\u043E \u0444\u0430\u0439\u043B\u0430.");
    return;
  }
  let targetGraph;
  if (file.path.includes(plugin.settings.paths.void)) {
    targetGraph = VOID;
  } else if (file.path.includes(plugin.settings.paths.celestia)) {
    targetGraph = CELESTIA;
  } else {
    new import_obsidian2.Notice("\u0424\u0430\u0439\u043B \u043D\u0435 \u043F\u0440\u0438\u043D\u0430\u0434\u043B\u0435\u0436\u0438\u0442 \u043D\u0438 \u043A VOID, \u043D\u0438 \u043A CELESTIA.");
    return;
  }
  const updater = new Updater(plugin);
  await updater.update(file, targetGraph, CELESTIA);
}

// src/commands/all_note_update.ts
async function updateAllLinks(plugin) {
  const repository = new Repo(plugin);
  const updater = new Updater(plugin);
  const allFiles = plugin.app.vault.getMarkdownFiles();
  const voidFiles = allFiles.filter(
    (file) => file.path.startsWith(plugin.settings.paths.void)
  );
  const celestiaFiles = allFiles.filter(
    (file) => file.path.startsWith(plugin.settings.paths.celestia)
  );
  const VOID = repository.createGraph(
    voidFiles,
    plugin.settings.paths.void,
    plugin.settings.aliases.void
  );
  const CELESTIA = repository.createGraph(
    celestiaFiles,
    plugin.settings.paths.celestia,
    plugin.settings.aliases.celestia
  );
  CELESTIA.files.sort((a, b) => a.basename.localeCompare(b.basename));
  console.log(`\u041D\u0430\u0447\u0430\u043B\u043E Celestia (${CELESTIA.files.length} \u0444\u0430\u0439\u043B\u043E\u0432)`);
  for (const file of CELESTIA.files) {
    await updater.update(file, CELESTIA, CELESTIA);
  }
  console.log("\u2713 Celestia \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043D\u0430");
  const rootFiles = [];
  const nestedFiles = [];
  for (const file of VOID.files) {
    if (file.basename.includes(".")) {
      nestedFiles.push(file);
    } else {
      rootFiles.push(file);
    }
  }
  console.log(`\u041D\u0430\u0447\u0430\u043B\u043E \u043A\u043E\u0440\u043D\u0435\u0432\u044B\u0445 Void (${rootFiles.length} \u0444\u0430\u0439\u043B\u043E\u0432)`);
  await processBatch(rootFiles, 50, updater, VOID, CELESTIA);
  console.log("\u2713 \u041A\u043E\u0440\u043D\u0435\u0432\u044B\u0435 Void \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043D\u044B");
  console.log(`\u041D\u0430\u0447\u0430\u043B\u043E \u0432\u043B\u043E\u0436\u0435\u043D\u043D\u044B\u0445 Void (${nestedFiles.length} \u0444\u0430\u0439\u043B\u043E\u0432)`);
  await processBatch(nestedFiles, 200, updater, VOID, CELESTIA);
  console.log("\u2713 \u0412\u043B\u043E\u0436\u0435\u043D\u043D\u044B\u0435 Void \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043D\u044B");
}
async function processBatch(files, batchSize, updater, graph, celestia) {
  for (let i = 0; i < files.length; i += batchSize) {
    const batch = files.slice(i, i + batchSize);
    await Promise.all(batch.map((file) => updater.update(file, graph, celestia)));
  }
}

// src/commands/new_event.ts
var import_obsidian3 = require("obsidian");
var EventTypeModal = class extends import_obsidian3.Modal {
  constructor(app, eventTypes, onSubmit) {
    super(app);
    this.eventTypes = eventTypes;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0442\u0438\u043F \u0441\u043E\u0431\u044B\u0442\u0438\u044F" });
    const listContainer = contentEl.createDiv("event-type-list");
    this.eventTypes.forEach((type) => {
      const button = listContainer.createEl("button", {
        text: type,
        cls: "event-type-button"
      });
      button.addEventListener("click", () => {
        this.close();
        this.onSubmit(type);
      });
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
async function createNewEvent(plugin) {
  const file = plugin.app.workspace.getActiveFile();
  if (!file) {
    new import_obsidian3.Notice("\u041D\u0435\u0442 \u0430\u043A\u0442\u0438\u0432\u043D\u043E\u0433\u043E \u0444\u0430\u0439\u043B\u0430");
    return;
  }
  const title = file.basename;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(title)) {
    new import_obsidian3.Notice("\u0417\u0430\u043C\u0435\u0442\u043A\u0430 \u043D\u0435 \u044F\u0432\u043B\u044F\u0435\u0442\u0441\u044F \u0435\u0436\u0435\u0434\u043D\u0435\u0432\u043D\u043E\u0439");
    return;
  }
  const allFiles = plugin.app.vault.getMarkdownFiles();
  const voidFiles = allFiles.filter(
    (file2) => file2.path.startsWith(plugin.settings.paths.void)
  );
  const celestiaFiles = allFiles.filter(
    (file2) => file2.path.startsWith(plugin.settings.paths.celestia)
  );
  let eventType;
  const pluginManager = plugin.app.plugins;
  if (pluginManager.plugins.templater) {
    eventType = await pluginManager.plugins.templater.templater.current_functions_object.system.suggester(
      plugin.settings.event.types,
      plugin.settings.event.types
    );
  } else {
    eventType = await new Promise((resolve) => {
      new EventTypeModal(plugin.app, plugin.settings.event.types, (selected) => {
        resolve(selected);
      }).open();
    });
  }
  if (!eventType) return;
  const eventPrefix = eventType.charAt(0).toLowerCase() + eventType.slice(1);
  const eventFiles = voidFiles.filter(
    (file2) => file2.basename.startsWith(`${eventPrefix}.${title}.<`)
  );
  let maxNumber = 0;
  eventFiles.forEach((file2) => {
    const match = file2.basename.match(/<(\d+)>/);
    if (match) {
      const number = parseInt(match[1]);
      if (number > maxNumber) maxNumber = number;
    }
  });
  const newFileName = `${plugin.settings.paths.void}${eventPrefix}.${title}.<${maxNumber + 1}>.md`;
  try {
    const createdFile = await plugin.app.vault.create(newFileName, "");
    new import_obsidian3.Notice(`\u0421\u043E\u0437\u0434\u0430\u043D: ${eventPrefix}.<${maxNumber + 1}>`);
    const repository = new Repo(plugin);
    const VOID = repository.createGraph(
      voidFiles,
      plugin.settings.paths.void,
      plugin.settings.aliases.void
    );
    const CELESTIA = repository.createGraph(
      celestiaFiles,
      plugin.settings.paths.celestia,
      plugin.settings.aliases.celestia
    );
    VOID.files.push(createdFile);
    VOID.files.sort((a, b) => a.basename.localeCompare(b.basename));
    const updater = new Updater(plugin);
    await updater.update(createdFile, VOID, CELESTIA);
    new import_obsidian3.Notice(`\u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u043E: ${eventPrefix}.<${maxNumber + 1}>`);
  } catch (error) {
    console.error(`\u041E\u0448\u0438\u0431\u043A\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u044F: ${error}`);
    new import_obsidian3.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u0438 \u0444\u0430\u0439\u043B\u0430");
  }
}

// src/commands/add_relative.ts
var import_obsidian5 = require("obsidian");

// src/ui/modal.ts
var import_obsidian4 = require("obsidian");
var ConfirmationModal = class extends import_obsidian4.Modal {
  constructor(app, message, action) {
    super(app);
    this.message = message;
    this.action = action;
  }
  onOpen() {
    const { contentEl } = this;
    this.modalEl.addClass("custom-unified-modal");
    contentEl.createEl("h2", { text: "\u041F\u043E\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043D\u0438\u0435" });
    contentEl.createEl("p", { text: this.message });
    const buttonContainer = contentEl.createDiv("modal-button-container");
    const cancelBtn = buttonContainer.createEl("button", { text: "\u041E\u0442\u043C\u0435\u043D\u0430" });
    cancelBtn.addEventListener("click", () => this.close());
    const confirmBtn = buttonContainer.createEl("button", {
      attr: { type: "submit" },
      cls: "mod-cta",
      text: "\u041F\u043E\u0434\u0442\u0432\u0435\u0440\u0434\u0438\u0442\u044C"
    });
    confirmBtn.addEventListener("click", async () => {
      this.close();
      await this.action();
    });
    contentEl.addEventListener("keydown", (e) => {
      if (e.key === "ArrowRight" || e.key === "ArrowLeft") {
        e.preventDefault();
        if (document.activeElement === confirmBtn) {
          cancelBtn.focus();
        } else {
          confirmBtn.focus();
        }
      }
    });
    setTimeout(() => confirmBtn.focus(), 50);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PromptModal = class extends import_obsidian4.Modal {
  constructor(app, promptText, onSubmit) {
    super(app);
    this.promptText = promptText;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    this.modalEl.addClass("custom-unified-modal");
    contentEl.createEl("h2", { text: this.promptText });
    const inputContainer = contentEl.createDiv("prompt-input-container");
    const input = inputContainer.createEl("input", { type: "text", cls: "prompt-input" });
    const buttonContainer = contentEl.createDiv("modal-button-container");
    const cancelBtn = buttonContainer.createEl("button", { text: "\u041E\u0442\u043C\u0435\u043D\u0430" });
    cancelBtn.addEventListener("click", () => this.close());
    const submitBtn = buttonContainer.createEl("button", {
      text: "\u041F\u043E\u0434\u0442\u0432\u0435\u0440\u0434\u0438\u0442\u044C",
      cls: "mod-cta"
    });
    submitBtn.addEventListener("click", () => {
      if (input.value.trim() !== "") {
        this.close();
        this.onSubmit(input.value.trim());
      }
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && input.value.trim() !== "") {
        e.preventDefault();
        this.close();
        this.onSubmit(input.value.trim());
      }
    });
    setTimeout(() => input.focus(), 50);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/commands/add_relative.ts
async function openOrCreateFather(plugin) {
  var _a;
  const file = plugin.app.workspace.getActiveFile();
  if (!file) {
    new import_obsidian5.Notice("\u041D\u0435\u0442 \u0430\u043A\u0442\u0438\u0432\u043D\u043E\u0433\u043E \u0444\u0430\u0439\u043B\u0430");
    return;
  }
  const words = file.basename.split(".");
  if (words.length <= 1) {
    new import_obsidian5.Notice("\u0423 \u044D\u0442\u043E\u0439 \u0437\u0430\u043C\u0435\u0442\u043A\u0438 \u043D\u0435 \u043C\u043E\u0436\u0435\u0442 \u0431\u044B\u0442\u044C \u043E\u0442\u0446\u0430 (\u043E\u043D\u0430 \u043A\u043E\u0440\u043D\u0435\u0432\u0430\u044F)");
    return;
  }
  const folderPath = file.parent && file.parent.path !== "/" ? `${file.parent.path}/` : "";
  const fatherName = words.slice(0, -1).join(".");
  const fatherPath = `${folderPath}${fatherName}.md`;
  try {
    let fatherFile = plugin.app.vault.getAbstractFileByPath(fatherPath);
    if (!fatherFile) {
      const fatherTitle = (_a = words[words.length - 2]) != null ? _a : fatherName;
      fatherFile = await plugin.app.vault.create(fatherPath, `# ${fatherTitle}
`);
      await updateAndOpen(plugin, fatherFile, fatherName, "\u043E\u0442\u0435\u0446");
    } else if (fatherFile instanceof import_obsidian5.TFile) {
      await plugin.app.workspace.getLeaf(false).openFile(fatherFile);
      new import_obsidian5.Notice(`\u041E\u0442\u0435\u0446 \u043E\u0442\u043A\u0440\u044B\u0442: ${fatherName}`);
    }
  } catch (e) {
    new import_obsidian5.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u043F\u043E\u0438\u0441\u043A\u0435 \u0438\u043B\u0438 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u0438 \u043E\u0442\u0446\u0430");
  }
}
async function createChild(plugin) {
  const file = plugin.app.workspace.getActiveFile();
  if (!file) {
    new import_obsidian5.Notice("\u041D\u0435\u0442 \u0430\u043A\u0442\u0438\u0432\u043D\u043E\u0433\u043E \u0444\u0430\u0439\u043B\u0430");
    return;
  }
  const folderPath = file.parent && file.parent.path !== "/" ? `${file.parent.path}/` : "";
  new PromptModal(plugin.app, "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0438\u043C\u044F \u0440\u0435\u0431\u0451\u043D\u043A\u0430:", async (inputName) => {
    const newName = `${file.basename}.${inputName}`;
    const newPath = `${folderPath}${newName}.md`;
    try {
      const existingFile = plugin.app.vault.getAbstractFileByPath(newPath);
      if (existingFile instanceof import_obsidian5.TFile) {
        await plugin.app.workspace.getLeaf(false).openFile(existingFile);
        new import_obsidian5.Notice(`\u0420\u0435\u0431\u0451\u043D\u043E\u043A \u043E\u0442\u043A\u0440\u044B\u0442: ${newName}`);
      } else {
        const newFile = await plugin.app.vault.create(newPath, `# ${inputName}
`);
        await updateAndOpen(plugin, newFile, newName, "\u0440\u0435\u0431\u0451\u043D\u043E\u043A");
      }
    } catch (e) {
      new import_obsidian5.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u044F \u0444\u0430\u0439\u043B\u0430");
    }
  }).open();
}
async function createBrother(plugin) {
  const file = plugin.app.workspace.getActiveFile();
  if (!file) {
    new import_obsidian5.Notice("\u041D\u0435\u0442 \u0430\u043A\u0442\u0438\u0432\u043D\u043E\u0433\u043E \u0444\u0430\u0439\u043B\u0430");
    return;
  }
  const words = file.basename.split(".");
  if (words.length <= 1) {
    new import_obsidian5.Notice("\u0423 \u043A\u043E\u0440\u043D\u0435\u0432\u043E\u0439 \u0437\u0430\u043C\u0435\u0442\u043A\u0438 \u043D\u0435 \u043C\u043E\u0436\u0435\u0442 \u0431\u044B\u0442\u044C \u0431\u0440\u0430\u0442\u0430 \u0442\u0430\u043A\u0438\u043C \u0441\u043F\u043E\u0441\u043E\u0431\u043E\u043C");
    return;
  }
  const folderPath = file.parent && file.parent.path !== "/" ? `${file.parent.path}/` : "";
  new PromptModal(plugin.app, "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0438\u043C\u044F \u0431\u0440\u0430\u0442\u0430:", async (inputName) => {
    const fatherName = words.slice(0, -1).join(".");
    const newName = `${fatherName}.${inputName}`;
    const newPath = `${folderPath}${newName}.md`;
    try {
      const existingFile = plugin.app.vault.getAbstractFileByPath(newPath);
      if (existingFile instanceof import_obsidian5.TFile) {
        await plugin.app.workspace.getLeaf(false).openFile(existingFile);
        new import_obsidian5.Notice(`\u0411\u0440\u0430\u0442 \u043E\u0442\u043A\u0440\u044B\u0442: ${newName}`);
      } else {
        const currentText = await plugin.app.vault.read(file);
        const headers = currentText.split("\n").filter((line) => line.startsWith("#")).join("\n");
        const currentTitle = words[words.length - 1];
        const initialContent = headers ? headers.replace(new RegExp(`# ${currentTitle}`, "g"), `# ${inputName}`) : `# ${inputName}
`;
        const newFile = await plugin.app.vault.create(newPath, initialContent);
        await updateAndOpen(plugin, newFile, newName, "\u0431\u0440\u0430\u0442");
      }
    } catch (e) {
      new import_obsidian5.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u044F \u0431\u0440\u0430\u0442\u0430");
    }
  }).open();
}
async function updateAndOpen(plugin, file, name, type) {
  const allFiles = plugin.app.vault.getMarkdownFiles();
  const voidFiles = allFiles.filter((f) => f.path.startsWith(plugin.settings.paths.void));
  const celestiaFiles = allFiles.filter(
    (f) => f.path.startsWith(plugin.settings.paths.celestia)
  );
  const repository = new Repo(plugin);
  const VOID = repository.createGraph(
    voidFiles,
    plugin.settings.paths.void,
    plugin.settings.aliases.void
  );
  const CELESTIA = repository.createGraph(
    celestiaFiles,
    plugin.settings.paths.celestia,
    plugin.settings.aliases.celestia
  );
  let targetGraph = null;
  if (file.path.includes(plugin.settings.paths.void)) {
    targetGraph = VOID;
  } else if (file.path.includes(plugin.settings.paths.celestia)) {
    targetGraph = CELESTIA;
  }
  if (targetGraph) {
    const updater = new Updater(plugin);
    await updater.update(file, targetGraph, CELESTIA);
  }
  await plugin.app.workspace.getLeaf(false).openFile(file);
  new import_obsidian5.Notice(`\u0421\u043E\u0437\u0434\u0430\u043D \u0438 \u043E\u0431\u043D\u043E\u0432\u043B\u0451\u043D ${type}: ${name}`);
}

// src/settings/settings.ts
var import_obsidian6 = require("obsidian");
var DEFAULT_SETTINGS = {
  paths: {
    void: "master/<9> void/",
    celestia: "master/<-9> celestia/"
  },
  aliases: {
    void: {
      founder: "herald",
      ancestor: "bubble",
      father: "arm"
    },
    celestia: {
      founder: "archont",
      ancestor: "band",
      father: "mate"
    }
  },
  tags: {
    mapping: {
      "\u2764\uFE0F\u200D\u{1F525}": "\u0440\u0435\u0430\u043B\u0438\u0437\u0430\u0446\u0438\u044F",
      "\u{1FAA8}": "\u043B\u0438\u0447\u043D\u043E\u0435",
      "\u{1F30A}": "\u0434\u0443\u0445\u043E\u0432\u043D\u043E\u0441\u0442\u044C",
      "\u{1F32C}\uFE0F": "\u0441\u0430\u043C\u043E\u0440\u0430\u0437\u0432\u0438\u0442\u0438\u0435"
    }
  },
  periodic: {
    templates: {
      daily: "0000-00-00",
      weekly: "0000-W00",
      monthly: "0000-00",
      quarterly: "0000-Q0",
      yearly: "0000"
    },
    celestia_paths: {
      daily: "\u2764\uFE0F\u200D\u{1F525}.\u043A\u0430\u043B\u0435\u043D\u0434\u0430\u0440\u044C.\u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0438\u0435.\u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0430\u044F.daily",
      weekly: "\u2764\uFE0F\u200D\u{1F525}.\u043A\u0430\u043B\u0435\u043D\u0434\u0430\u0440\u044C.\u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0438\u0435.\u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0430\u044F.weekly",
      monthly: "\u2764\uFE0F\u200D\u{1F525}.\u043A\u0430\u043B\u0435\u043D\u0434\u0430\u0440\u044C.\u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0438\u0435.\u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0430\u044F.monthly",
      quarterly: "\u2764\uFE0F\u200D\u{1F525}.\u043A\u0430\u043B\u0435\u043D\u0434\u0430\u0440\u044C.\u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0438\u0435.\u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0430\u044F.quarterly",
      yearly: "\u2764\uFE0F\u200D\u{1F525}.\u043A\u0430\u043B\u0435\u043D\u0434\u0430\u0440\u044C.\u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0438\u0435.\u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0430\u044F.monthly"
    }
  },
  event: {
    types: ["\u0421\u043E\u043D", "\u041C\u044B\u0441\u043B\u044C", "\u0410\u043D\u0430\u043B\u0438\u0437", "\u0421\u0430\u043C\u043E\u0430\u043D\u0430\u043B\u0438\u0437"]
  }
};
var PeriodicNotesSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Periodic Notes Linker - \u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438" });
    containerEl.createEl("h3", { text: "\u041F\u0443\u0442\u0438 \u043A \u043F\u0430\u043F\u043A\u0430\u043C" });
    new import_obsidian6.Setting(containerEl).setName("\u041F\u0443\u0442\u044C \u043A Void").setDesc("\u041F\u0443\u0442\u044C \u043A \u043F\u0430\u043F\u043A\u0435 \u0441 \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u043C\u0438 Void").addText(
      (text) => text.setPlaceholder("master/<9> void/").setValue(this.plugin.settings.paths.void).onChange(async (value) => {
        this.plugin.settings.paths.void = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u041F\u0443\u0442\u044C \u043A Celestia").setDesc("\u041F\u0443\u0442\u044C \u043A \u043F\u0430\u043F\u043A\u0435 \u0441 \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u043C\u0438 Celestia").addText(
      (text) => text.setPlaceholder("master/<-9> celestia/").setValue(this.plugin.settings.paths.celestia).onChange(async (value) => {
        this.plugin.settings.paths.celestia = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u0410\u043B\u0438\u0430\u0441\u044B \u0434\u043B\u044F Void" });
    new import_obsidian6.Setting(containerEl).setName("Void: \u041E\u0441\u043D\u043E\u0432\u0430\u0442\u0435\u043B\u044C (Founder)").addText(
      (text) => text.setPlaceholder("herald").setValue(this.plugin.settings.aliases.void.founder).onChange(async (value) => {
        this.plugin.settings.aliases.void.founder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Void: \u041F\u0440\u0435\u0434\u043E\u043A (Ancestor)").addText(
      (text) => text.setPlaceholder("bubble").setValue(this.plugin.settings.aliases.void.ancestor).onChange(async (value) => {
        this.plugin.settings.aliases.void.ancestor = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Void: \u0420\u043E\u0434\u0438\u0442\u0435\u043B\u044C (Father)").addText(
      (text) => text.setPlaceholder("arm").setValue(this.plugin.settings.aliases.void.father).onChange(async (value) => {
        this.plugin.settings.aliases.void.father = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u0410\u043B\u0438\u0430\u0441\u044B \u0434\u043B\u044F Celestia" });
    new import_obsidian6.Setting(containerEl).setName("Celestia: \u041E\u0441\u043D\u043E\u0432\u0430\u0442\u0435\u043B\u044C (Founder)").addText(
      (text) => text.setPlaceholder("archont").setValue(this.plugin.settings.aliases.celestia.founder).onChange(async (value) => {
        this.plugin.settings.aliases.celestia.founder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Celestia: \u041F\u0440\u0435\u0434\u043E\u043A (Ancestor)").addText(
      (text) => text.setPlaceholder("band").setValue(this.plugin.settings.aliases.celestia.ancestor).onChange(async (value) => {
        this.plugin.settings.aliases.celestia.ancestor = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Celestia: \u0420\u043E\u0434\u0438\u0442\u0435\u043B\u044C (Father)").addText(
      (text) => text.setPlaceholder("mate").setValue(this.plugin.settings.aliases.celestia.father).onChange(async (value) => {
        this.plugin.settings.aliases.celestia.father = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u041C\u0430\u043F\u043F\u0438\u043D\u0433 \u0442\u0435\u0433\u043E\u0432" });
    const tagMappings = [
      { emoji: "\u2764\uFE0F\u200D\u{1F525}", name: "\u0420\u0435\u0430\u043B\u0438\u0437\u0430\u0446\u0438\u044F", key: "\u2764\uFE0F\u200D\u{1F525}" },
      { emoji: "\u{1FAA8}", name: "\u041B\u0438\u0447\u043D\u043E\u0435", key: "\u{1FAA8}" },
      { emoji: "\u{1F30A}", name: "\u0414\u0443\u0445\u043E\u0432\u043D\u043E\u0441\u0442\u044C", key: "\u{1F30A}" },
      { emoji: "\u{1F32C}\uFE0F", name: "\u0421\u0430\u043C\u043E\u0440\u0430\u0437\u0432\u0438\u0442\u0438\u0435", key: "\u{1F32C}\uFE0F" }
    ];
    tagMappings.forEach(({ emoji, name, key }) => {
      new import_obsidian6.Setting(containerEl).setName(`${emoji} \u2192`).addText(
        (text) => text.setPlaceholder(name.toLowerCase()).setValue(this.plugin.settings.tags.mapping[key]).onChange(async (value) => {
          this.plugin.settings.tags.mapping[key] = value;
          await this.plugin.saveSettings();
        })
      );
    });
    containerEl.createEl("h3", { text: "\u0428\u0430\u0431\u043B\u043E\u043D\u044B \u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0438\u0445 \u0437\u0430\u043C\u0435\u0442\u043E\u043A" });
    new import_obsidian6.Setting(containerEl).setName("\u0428\u0430\u0431\u043B\u043E\u043D Daily").addText(
      (text) => text.setPlaceholder("0000-00-00").setValue(this.plugin.settings.periodic.templates.daily).onChange(async (value) => {
        this.plugin.settings.periodic.templates.daily = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u0428\u0430\u0431\u043B\u043E\u043D Weekly").addText(
      (text) => text.setPlaceholder("0000-W00").setValue(this.plugin.settings.periodic.templates.weekly).onChange(async (value) => {
        this.plugin.settings.periodic.templates.weekly = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u0428\u0430\u0431\u043B\u043E\u043D Monthly").addText(
      (text) => text.setPlaceholder("0000-00").setValue(this.plugin.settings.periodic.templates.monthly).onChange(async (value) => {
        this.plugin.settings.periodic.templates.monthly = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u0428\u0430\u0431\u043B\u043E\u043D Quarterly").addText(
      (text) => text.setPlaceholder("0000-Q0").setValue(this.plugin.settings.periodic.templates.quarterly).onChange(async (value) => {
        this.plugin.settings.periodic.templates.quarterly = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u0428\u0430\u0431\u043B\u043E\u043D Yearly").addText(
      (text) => text.setPlaceholder("0000").setValue(this.plugin.settings.periodic.templates.yearly).onChange(async (value) => {
        this.plugin.settings.periodic.templates.yearly = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u041F\u0443\u0442\u0438 \u043A \u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0438\u043C \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u043C \u0432 Celestia" });
    new import_obsidian6.Setting(containerEl).setName("Daily \u043F\u0443\u0442\u044C").addText(
      (text) => text.setPlaceholder("\u2764\uFE0F\u200D\u{1F525}.\u043A\u0430\u043B\u0435\u043D\u0434\u0430\u0440\u044C.\u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0438\u0435.\u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0430\u044F.daily").setValue(this.plugin.settings.periodic.celestia_paths.daily).onChange(async (value) => {
        this.plugin.settings.periodic.celestia_paths.daily = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Weekly \u043F\u0443\u0442\u044C").addText(
      (text) => text.setValue(this.plugin.settings.periodic.celestia_paths.weekly).onChange(async (value) => {
        this.plugin.settings.periodic.celestia_paths.weekly = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Monthly \u043F\u0443\u0442\u044C").addText(
      (text) => text.setValue(this.plugin.settings.periodic.celestia_paths.monthly).onChange(async (value) => {
        this.plugin.settings.periodic.celestia_paths.monthly = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Quarterly \u043F\u0443\u0442\u044C").addText(
      (text) => text.setValue(this.plugin.settings.periodic.celestia_paths.quarterly).onChange(async (value) => {
        this.plugin.settings.periodic.celestia_paths.quarterly = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Yearly \u043F\u0443\u0442\u044C").addText(
      (text) => text.setValue(this.plugin.settings.periodic.celestia_paths.yearly).onChange(async (value) => {
        this.plugin.settings.periodic.celestia_paths.yearly = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u0422\u0438\u043F\u044B \u0441\u043E\u0431\u044B\u0442\u0438\u0439" });
    new import_obsidian6.Setting(containerEl).setName("\u0422\u0438\u043F\u044B \u0441\u043E\u0431\u044B\u0442\u0438\u0439").setDesc("\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0442\u0438\u043F\u044B \u0441\u043E\u0431\u044B\u0442\u0438\u0439 \u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043F\u044F\u0442\u0443\u044E").addText(
      (text) => text.setPlaceholder("\u0421\u043E\u043D, \u041C\u044B\u0441\u043B\u044C, \u0410\u043D\u0430\u043B\u0438\u0437, \u0421\u0430\u043C\u043E\u0430\u043D\u0430\u043B\u0438\u0437").setValue(this.plugin.settings.event.types.join(", ")).onChange(async (value) => {
        this.plugin.settings.event.types = value.split(",").map((s) => s.trim());
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u0421\u0431\u0440\u043E\u0441\u0438\u0442\u044C \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438").setDesc("\u0412\u0435\u0440\u043D\u0443\u0442\u044C \u0432\u0441\u0435 \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u043A \u0437\u043D\u0430\u0447\u0435\u043D\u0438\u044F\u043C \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E").addButton(
      (button) => button.setButtonText("\u0421\u0431\u0440\u043E\u0441\u0438\u0442\u044C").setWarning().onClick(async () => {
        this.plugin.settings = JSON.parse(JSON.stringify(DEFAULT_SETTINGS));
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
};

// src/main.ts
var PeriodicNotesPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    console.log("\u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430 Periodic Notes Linker");
    await this.loadSettings();
    this.addSettingTab(new PeriodicNotesSettingTab(this.app, this));
    this.addCommand({
      id: "update-links-of-note",
      name: "\u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C \u0441\u0441\u044B\u043B\u043A\u0438 \u0437\u0430\u043C\u0435\u0442\u043A\u0438",
      callback: async () => {
        new import_obsidian7.Notice("\u041D\u0430\u0447\u0430\u0442\u043E \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435 \u0441\u0441\u044B\u043B\u043E\u043A \u0437\u0430\u043C\u0435\u0442\u043A\u0438");
        try {
          await updateNoteLinks(this);
          new import_obsidian7.Notice("\u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435 \u0441\u0441\u044B\u043B\u043E\u043A \u0437\u0430\u043C\u0435\u0442\u043A\u0438 \u0437\u0430\u043A\u043E\u043D\u0447\u0435\u043D\u043E");
        } catch (e) {
          new import_obsidian7.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0438 \u0441\u0441\u044B\u043B\u043E\u043A");
        }
      }
    });
    this.addCommand({
      id: "update-links-of-vault",
      name: "\u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C \u0441\u0441\u044B\u043B\u043A\u0438 \u0445\u0440\u0430\u043D\u0438\u043B\u0438\u0449\u0430",
      callback: async () => {
        new ConfirmationModal(
          this.app,
          "\u042D\u0442\u043E \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u043E\u0431\u043D\u043E\u0432\u0438\u0442 \u0441\u0441\u044B\u043B\u043A\u0438 \u0432\u043E \u0432\u0441\u0435\u0445 \u0444\u0430\u0439\u043B\u0430\u0445. \u0412\u044B \u0443\u0432\u0435\u0440\u0435\u043D\u044B?",
          async () => {
            new import_obsidian7.Notice("\u041D\u0430\u0447\u0430\u0442\u043E \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435 \u0441\u0441\u044B\u043B\u043E\u043A \u0445\u0440\u0430\u043D\u0438\u043B\u0438\u0449\u0430");
            try {
              await updateAllLinks(this);
              new import_obsidian7.Notice("\u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435 \u0441\u0441\u044B\u043B\u043E\u043A \u0445\u0440\u0430\u043D\u0438\u043B\u0438\u0449\u0430 \u0437\u0430\u043A\u043E\u043D\u0447\u0435\u043D\u043E");
            } catch (e) {
              new import_obsidian7.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0438 \u0445\u0440\u0430\u043D\u0438\u043B\u0438\u0449\u0430");
            }
          }
        ).open();
      }
    });
    this.addCommand({
      id: "create-new-periodic",
      name: "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u043D\u043E\u0432\u043E\u0435 \u043F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u043E\u0435 \u0441\u043E\u0431\u044B\u0442\u0438\u0435",
      callback: async () => {
        new import_obsidian7.Notice("\u0421\u043E\u0437\u0434\u0430\u043D\u0438\u0435 \u043D\u0430\u0447\u0430\u0442\u043E");
        try {
          await createNewEvent(this);
          new import_obsidian7.Notice("\u0421\u043E\u0437\u0434\u0430\u043D\u0438\u0435 \u0437\u0430\u043A\u043E\u043D\u0447\u0435\u043D\u043E");
        } catch (e) {
          new import_obsidian7.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u0438");
        }
      }
    });
    this.addCommand({
      id: "open-create-father-note",
      name: "\u041E\u0442\u043A\u0440\u044B\u0442\u044C/\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u043E\u0442\u0446\u0430 \u0434\u043B\u044F \u0442\u0435\u043A\u0443\u0449\u0435\u0439 \u0437\u0430\u043C\u0435\u0442\u043A\u0438",
      callback: async () => {
        try {
          await openOrCreateFather(this);
        } catch (e) {
          new import_obsidian7.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u043E\u0431\u0440\u0430\u0431\u043E\u0442\u043A\u0435 \u043E\u0442\u0446\u0430");
        }
      }
    });
    this.addCommand({
      id: "create-child-note",
      name: "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u0440\u0435\u0431\u0451\u043D\u043A\u0430 \u0434\u043B\u044F \u0442\u0435\u043A\u0443\u0449\u0435\u0439 \u0437\u0430\u043C\u0435\u0442\u043A\u0438",
      callback: async () => {
        try {
          await createChild(this);
        } catch (e) {
          new import_obsidian7.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u0438 \u0440\u0435\u0431\u0451\u043D\u043A\u0430");
        }
      }
    });
    this.addCommand({
      id: "create-brother-note",
      name: "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u0431\u0440\u0430\u0442\u0430 \u0434\u043B\u044F \u0442\u0435\u043A\u0443\u0449\u0435\u0439 \u0437\u0430\u043C\u0435\u0442\u043A\u0438",
      callback: async () => {
        try {
          await createBrother(this);
        } catch (e) {
          new import_obsidian7.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u0438 \u0431\u0440\u0430\u0442\u0430");
        }
      }
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
    console.log("\u0412\u044B\u0433\u0440\u0443\u0437\u043A\u0430 Periodic Notes Linker");
  }
};
